### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by nyagasan** [KaguraGateway/UniversalSwapDiary#6]
- [x] トーンマナーの制定
- [x] フォント選定

**Comment by nyagasan** [comment]
@Yamamoto1012 
メインカラー、どれが一番かわいいと思う？
直感でいいから教えてほしい〜
![Frame 10 (1)](https://github.com/KaguraGateway/UniversalSwapDiary/assets/107671385/248a1a2f-79b0-47bb-aa6c-acd2ec5634eb)

**Comment by Yamamoto1012** [comment]
赤っぽいやつ

**Comment by nyagasan** [comment]
ありがと〜
赤ベースでデザインするね👍

> 赤っぽいやつ

**Comment by nyagasan** [comment]
ベースカラーはFFD6DB、フォントはZen MaruGothicでいきます
